Fix `libfbjs`.
Summary:
Currently, I am unable to build `libfbjs`. More specifically, I get the following error:

```
g++  -fPIC -Wall -DNOT_FBMAKE=1 -ggdb -g -O0 -DDEBUG  -c -o parser.yacc.o parser.yacc.cpp
In file included from parser.hpp:35:0,
                 from parser.yy:23:
parser.yacc.hpp:186:31: error: ‘Node’ has not been declared
 int yyparse (void* yyscanner, Node* root);
                               ^
make: *** [parser.yacc.o] Error 1
```

It seems that the issue is that in the generated `parser.yacc.hpp`, `Node` isn't fully qualified with the correct namespace (i.e. `libfbjs::Node`). Comparing `parser.y` from `libfbjs` with the same file from `xhpast`, it seems that the namespace is missing from `libfbjs`.

Test Plan: After this change, I am able to build `libfbjs` using `make`.

Reviewers: #blessed_reviewers, epriestley

Subscribers: epriestley, Korvin

Differential Revision: https://secure.phabricator.com/D9446