Add JX.$E() that throws an exception and attached caller info the exception message.
Summary:
JX.$() errors should be common and difficult to debug. Reproducing the errors
is often the hardest part. This diff should make the debugging a lot easier.
This problem should be common for all developers, not just FB.

I'm keeping it as simple as possible but sufficient for handling the
most frequent problem. We could potentially print callstack instead of
caller.. That shouldn't be too hard to do if desirable.

Test Plan:
The exception message before and after.

Before:

Exception: {"message":"JX.$('u402390_1a') call matched no nodes.

After:

Exception: {"message":"JX.$('u402390_1a') call matched no nodes. Caller:\
function (config) {\
  var sources = [];\
  if (config.sources.bootstrapped) {\
    sources.push(new JX.MTypeaheadTouchSource(\
      config.sources.bootstrapped.src,\
      config.sources.bootstrapped.source_key\
    ));\
  }\
  if (config.sources.online) {\
    sources.push(new JX.MTypeaheadOnDemandSource(config.sources.online.src));\
  }\
\
  var hardpoint = JX.$(config.id+'a');\
  var input = JX.$(config.textinput);\
  var content = JX.$('sections');\
  var shadow = JX.$('sections.shadow');\
  var button = JX.DOM.find(hardpoint, 'button', 'friends-search-button');\
  var typeahead = new JX.MSearchFriendsTypeahead(hardpoint, input);\
  typeahead.setDatasource(new JX.TypeaheadCompositeSource(sources));\
\
  if (!config.navigateOnSelect) {\
    // This is needed to explicitly kill click events from Touchable JS,\
    // which will otherwise result in following the href for a result anchor.\
    JX.DOM.listen(hardpoint, 'click', 'typeahead-result', function(e) {\
      e.kill();\
    });\
  }\

Revert Plan:

Tags:

Reviewers: epriestley, mroch, phil, aran, leebyron, yungsters, tomo, guangyuc,
jg, lukeshepard

Reviewed By: epriestley

CC: aran, epriestley, guilin, phil, guangyuc

Differential Revision: 956